# Generated by Django 6.0 on 2025-12-26 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('barcode', models.CharField(max_length=50, unique=True, verbose_name='Plaka Barkodu/No')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Kalınlık (mm)')),
                ('status', models.CharField(choices=[('AVAILABLE', 'Stokta'), ('RESERVED', 'Rezerve (Projeye Atandı)'), ('USED', 'Kesildi/Kullanıldı'), ('SOLD', 'Doğrudan Satıldı')], default='AVAILABLE', max_length=20)),
                ('warehouse_location', models.CharField(blank=True, help_text='Depo Raf/Bölüm Kodu', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slabs', to='inventory.productdefinition')),
                ('reserved_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
