# Generated by Django 6.0 on 2025-12-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slab',
            name='fire_disposition',
            field=models.CharField(blank=True, choices=[('UNKNOWN', 'Belirtilmedi'), ('PART_STOCK', 'Parça Stok'), ('SCRAP', 'Çöp/Fire')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='slab',
            name='reserved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slab',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Stokta'), ('RESERVED', 'Rezerve (Projeye Atandı)'), ('USED', 'Kesildi/Kullanıldı'), ('SOLD', 'Doğrudan Satıldı'), ('PART_STOCK', 'Parça Stok'), ('SCRAP', 'Çöp/Fire')], default='AVAILABLE', max_length=20),
        ),
    ]
