# Generated by Django 6.0 on 2025-12-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_slab_fire_disposition_slab_reserved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slab',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='slabs/', verbose_name='Plaka Fotoğrafı'),
        ),
    ]
