# Generated by Django 6.0 on 2025-12-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_slab_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='slab',
            name='photo_url',
            field=models.URLField(blank=True, verbose_name='Plaka Fotoğraf URL'),
        ),
    ]
