# Generated by Django 6.0 on 2025-12-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_slab_photo_url"),
        ("production", "0004_contract_enhancements_and_workorder_plan"),
        ("crm", "0005_proposalitem_slab_and_approval_flow"),
    ]

    operations = [
        migrations.AddField(
            model_name="slab",
            name="soft_reserved_for",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="soft_reserved_slabs", to="production.contract"),
        ),
        migrations.AddField(
            model_name="slab",
            name="soft_reserved_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi")),
                ("area_m2", models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ("thickness_mm", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("status", models.CharField(choices=[("SOFT_RESERVED", "Soft Reserved"), ("HARD_RESERVED", "Hard Reserved"), ("RELEASED", "Released")], default="SOFT_RESERVED", max_length=20)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("release_reason", models.CharField(blank=True, default="", max_length=200)),
                ("contract", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="stock_reservations", to="production.contract")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="inventory.productdefinition")),
                ("proposal_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reservations", to="crm.proposalitem")),
                ("slab", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="inventory.slab")),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "unique_together": {("contract", "proposal_item")},
            },
        ),
    ]
