# Generated by Django 6.0 on 2025-12-26 21:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_alter_account_options_alter_account_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('role', models.CharField(choices=[('WORKER', 'Usta / Üretim Personeli'), ('SALES', 'Satış Temsilcisi'), ('OFFICE', 'Ofis / Yönetim'), ('DRIVER', 'Şoför / Lojistik')], default='WORKER', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('tc_number', models.CharField(blank=True, max_length=11, verbose_name='TC Kimlik No')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Net Maaş')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Personel')),
                ('account', models.OneToOneField(blank=True, help_text='Personel cari hesabı ile otomatik bağlantı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to='finance.account')),
            ],
            options={
                'verbose_name': 'Personel',
                'verbose_name_plural': 'Personeller',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('year', models.IntegerField(default=2025)),
                ('month', models.IntegerField(choices=[(1, 'Ocak'), (2, 'Şubat'), (3, 'Mart'), (4, 'Nisan'), (5, 'Mayıs'), (6, 'Haziran'), (7, 'Temmuz'), (8, 'Ağustos'), (9, 'Eylül'), (10, 'Ekim'), (11, 'Kasım'), (12, 'Aralık')])),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Hakedilen Maaş')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Mesai Saati')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Mesai Tutarı')),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Prim/Bonus')),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Kesinti/Avans')),
                ('note', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ödendi mi?')),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Bordro',
                'verbose_name_plural': 'Bordrolar',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month')},
            },
        ),
    ]
