# Generated by Django 6.0 on 2025-12-27

from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payroll",
            name="overtime_hourly_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[MinValueValidator(Decimal("0"))],
                verbose_name="Saat Ücreti (Mesai)",
            ),
        ),
    ]
