# Generated by Django 6.0 on 2025-12-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_payroll_overtime_hourly_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="hire_date",
            field=models.DateField(blank=True, null=True, verbose_name="İşe Giriş Tarihi"),
        ),
        migrations.AddField(
            model_name="employee",
            name="remaining_leave_days",
            field=models.IntegerField(default=0, verbose_name="Kalan İzin Günü"),
        ),
        migrations.AddField(
            model_name="employee",
            name="assigned_assets",
            field=models.JSONField(blank=True, default=list, verbose_name="Zimmetlenen Eşyalar"),
        ),
    ]
