# Generated by Django 6.0 on 2025-12-26 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('project_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('deadline_date', models.DateField(verbose_name='Teslim Tarihi')),
                ('contract_file', models.FileField(upload_to='contracts/', verbose_name='İmzalı Sözleşme PDF')),
                ('is_active', models.BooleanField(default=True)),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='crm.proposal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('title', models.CharField(help_text='Mutfak Tezgahı Kesimi vb.', max_length=200)),
                ('stage', models.CharField(choices=[('PENDING', 'Bekliyor'), ('CUTTING', 'Kesim'), ('POLISHING', 'Cila/Yüzey İşlem'), ('ASSEMBLY', 'Montaj (Saha)'), ('COMPLETED', 'Tamamlandı')], default='PENDING', max_length=20)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(default=1, verbose_name='Öncelik (1-5)')),
                ('assigned_team', models.ForeignKey(limit_choices_to={'role': 'PRODUCTION'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='production.contract')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('data', models.JSONField(default=dict, verbose_name='Ölçü Detayları (JSON)')),
                ('site_photo', models.ImageField(upload_to='measurements/', verbose_name='Saha Fotoğrafı')),
                ('sketch_image', models.ImageField(blank=True, null=True, upload_to='sketches/', verbose_name='El Çizimi/Kroki')),
                ('notes', models.TextField(blank=True)),
                ('taken_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='production.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
