# Generated by Django 6.0 on 2025-12-26 18:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='special_terms',
            field=models.TextField(blank=True, verbose_name='Özel Şartlar'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='İmzalı Sözleşme PDF'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
