# Generated by Django 6.0 on 2025-12-26 18:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_slab_fire_disposition_slab_reserved_at_and_more'),
        ('production', '0002_contract_special_terms_alter_contract_contract_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Aktif'), ('COMPLETED', 'Tamamlandı'), ('CANCELLED', 'İptal')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='measurement',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='production.contract'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='final_dimensions',
            field=models.JSONField(blank=True, default=dict, verbose_name='Net Ölçüler (JSON)'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='site_photos',
            field=models.JSONField(blank=True, default=list, verbose_name='Saha Fotoğrafları (Liste)'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='slab',
            field=models.ForeignKey(blank=True, help_text='Hangi plaka kesilecek?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='inventory.slab'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='production.workorder'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='stage',
            field=models.CharField(choices=[('PENDING', 'Bekliyor'), ('CUTTING', 'Kesim'), ('POLISHING', 'Cila/Yüzey İşlem'), ('READY', 'Sevkiyata Hazır'), ('ASSEMBLY', 'Montaj (Saha)'), ('COMPLETED', 'Tamamlandı')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('previous_stage', models.CharField(max_length=20)),
                ('new_stage', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='production.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
