# Generated by Django 6.0 on 2025-12-27

from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0003_contract_status_measurement_contract_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="contract_no",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="Sözleşme No"),
        ),
        migrations.AddField(
            model_name="contract",
            name="job_address",
            field=models.TextField(blank=True, default="", verbose_name="İş/Adres"),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_pdf",
            field=models.FileField(blank=True, null=True, upload_to="contracts/generated/", verbose_name="Otomatik Sözleşme PDF"),
        ),
        migrations.AddField(
            model_name="contract",
            name="contract_pdf_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contract",
            name="items_snapshot",
            field=models.JSONField(blank=True, default=list, verbose_name="Sözleşme Kalemleri (Snapshot)"),
        ),
        migrations.AddField(
            model_name="contract",
            name="customer_name",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="contract",
            name="customer_address",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="contract",
            name="customer_phone",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="contract",
            name="customer_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="contract",
            name="customer_tax_number",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="contract",
            name="customer_tax_office",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="contract",
            name="subtotal_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=19),
        ),
        migrations.AddField(
            model_name="contract",
            name="tax_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=19),
        ),
        migrations.AddField(
            model_name="contract",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=19),
        ),
        migrations.AddField(
            model_name="contract",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=19),
        ),
        migrations.AddField(
            model_name="contract",
            name="currency",
            field=models.CharField(default="TRY", max_length=3),
        ),
        migrations.AddField(
            model_name="contract",
            name="include_tax",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contract",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=Decimal("20.00"), max_digits=5),
        ),
        migrations.AddField(
            model_name="contract",
            name="valid_until",
            field=models.DateField(blank=True, null=True, verbose_name="Teklif Geçerlilik Tarihi"),
        ),
        migrations.AddField(
            model_name="contract",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("IMZA_BEKLIYOR", "İmza Bekliyor"),
                    ("IMZALANDI", "İmzalandı"),
                    ("ACTIVE", "Aktif"),
                    ("COMPLETED", "Tamamlandı"),
                    ("CANCELLED", "İptal"),
                ],
                default="IMZA_BEKLIYOR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="kind",
            field=models.CharField(
                choices=[
                    ("MEASUREMENT", "Saha Ölçü"),
                    ("PRODUCTION", "Üretim"),
                    ("DELIVERY", "Montaj/Teslim"),
                    ("GENERAL", "Genel"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="workorder",
            name="stage",
            field=models.CharField(
                choices=[
                    ("PLANLANACAK", "Planlanacak"),
                    ("PENDING", "Bekliyor"),
                    ("CUTTING", "Kesim"),
                    ("POLISHING", "Cila/Yüzey İşlem"),
                    ("READY", "Sevkiyata Hazır"),
                    ("ASSEMBLY", "Montaj (Saha)"),
                    ("COMPLETED", "Tamamlandı"),
                ],
                default="PLANLANACAK",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productionlog",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.CreateModel(
            name="ContractSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi")),
                ("year", models.PositiveSmallIntegerField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Sözleşme Seri",
                "verbose_name_plural": "Sözleşme Serileri",
            },
        ),
    ]
