# Generated by Django 6.0 on 2025-12-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_contract_enhancements_and_workorder_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_pdf',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_pdf_generated_at',
        ),
    ]
