# Generated by Django 6.0 on 2025-12-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi")),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("priority", models.PositiveSmallIntegerField(choices=[(1, "Düşük"), (2, "Normal"), (3, "Yüksek")], default=2)),
                ("status", models.CharField(choices=[("OPEN", "Açık"), ("DONE", "Tamamlandı"), ("CANCELLED", "İptal")], default="OPEN", max_length=20)),
                ("assigned_role", models.CharField(blank=True, choices=[("ADMIN", "Yönetici"), ("SALES", "Satış Temsilcisi"), ("FINANCE", "Finans/Muhasebe"), ("PRODUCTION", "Üretim/Saha")], default="", max_length=20)),
                ("related_url", models.CharField(blank=True, default="", max_length=300)),
                ("source_type", models.CharField(blank=True, default="", max_length=50)),
                ("source_id", models.PositiveIntegerField(blank=True, null=True)),
                ("assigned_to", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="tasks", to="core.user")),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SystemEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi")),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
