# Generated by Django 6.0 on 2025-12-26 13:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('production', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('name', models.CharField(max_length=100, verbose_name='Hesap Adı')),
                ('account_type', models.CharField(choices=[('CASH', 'Nakit Kasa'), ('BANK', 'Banka Hesabı'), ('POS', 'POS Hesabı'), ('CREDIT_CARD', 'Kredi Kartı'), ('PARTNER', 'Şirket Ortağı/Şahıs'), ('CUSTOMER', 'Müşteri Carisi'), ('VENDOR', 'Tedarikçi Carisi')], max_length=20)),
                ('currency', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro')], default='TRY', max_length=3)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Açılış Bakiyesi')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Güncel Bakiye')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Çek Seri No')),
                ('drawer_name', models.CharField(max_length=100, verbose_name='Keşideci (Çeki Veren)')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('due_date', models.DateField(verbose_name='Vade Tarihi')),
                ('status', models.CharField(choices=[('PORTFOLIO', 'Portföyde (Bizde)'), ('ENDORSED', 'Ciro Edildi (Başkasına Verildi)'), ('COLLECTED', 'Tahsil Edildi (Bankaya/Kasaya Geçti)'), ('BOUNCED', 'Karşılıksız/Sorunlu')], default='PORTFOLIO', max_length=20)),
                ('endorsed_to_supplier', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciro Edilen Kişi/Kurum')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cheques/', verbose_name='Çek Fotoğrafı')),
                ('received_from_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer', verbose_name='Alınan Müşteri')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('description', models.CharField(max_length=255, verbose_name='Açıklama')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transaction_date', models.DateField(verbose_name='İşlem Tarihi')),
                ('transaction_type', models.CharField(choices=[('PAYMENT', 'Ödeme'), ('COLLECTION', 'Tahsilat'), ('TRANSFER', 'Virman/Transfer'), ('EXPENSE', 'Gider Fişi')], max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_transactions', to='production.contract')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='finance.account', verbose_name='Kaynak Hesap (Çıkan)')),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='finance.account', verbose_name='Hedef Hesap (Giren)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
