# Generated by Django 6.0 on 2025-12-26 20:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_customer_google_maps_link_and_more'),
        ('finance', '0001_initial'),
        ('production', '0003_contract_status_measurement_contract_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Hesap/Kasa', 'verbose_name_plural': 'Hesaplar & Kasalar'},
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('name', 'currency')},
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='drawer_name',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='endorsed_to_supplier',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='image',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='account',
            name='cached_balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text="Performans amaçlı tutulur. Gerçek bakiye transaction'lardan hesaplanmalıdır.", max_digits=19, verbose_name='Cache Bakiye'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='currency',
            field=models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro')], default='TRY', max_length=3),
        ),
        migrations.AddField(
            model_name='cheque',
            name='current_location',
            field=models.CharField(blank=True, default='', help_text="Örn: Kasada, Meka Granit'te", max_length=200),
        ),
        migrations.AddField(
            model_name='cheque',
            name='drawer',
            field=models.CharField(default='', max_length=200, verbose_name='Keşideci (Çek Sahibi)'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='given_to_supplier',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Verilen Tedarikçi/Kişi'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='cheques/'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='cheques/'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='İşlem Tarihi'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='finance/receipts/', verbose_name='Dekont/Fiş'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='related_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Nakit Kasa'), ('BANK', 'Banka Hesabı'), ('POS', 'POS / Kredi Kartı'), ('EMPLOYEE', 'Personel Cari'), ('PARTNER', 'Ortak Cari (Şahsi)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='received_from_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_cheques', to='crm.customer', verbose_name='Alınan Müşteri'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('PORTFOLIO', 'Portföyde (Bizde)'), ('ENDORSED', 'Ciro Edildi (Tedarikçiye Verildi)'), ('BANK', 'Bankada (Tahsilde)'), ('COLLECTED', 'Tahsil Edildi'), ('BOUNCED', 'Karşılıksız/Döndü')], default='PORTFOLIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='related_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.contract'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='source_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='finance.account', verbose_name='Kaynak Hesap (Çıkan)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='target_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='finance.account', verbose_name='Hedef Hesap (Giren)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Tahsilat / Giriş'), ('EXPENSE', 'Ödeme / Çıkış'), ('TRANSFER', 'Virman / Transfer')], max_length=20),
        ),
        migrations.RemoveField(
            model_name='account',
            name='current_balance',
        ),
    ]
