# Generated by Django 6.0 on 2025-12-27

from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_alter_account_options_alter_account_unique_together_and_more"),
        ("production", "0002_contract_special_terms_alter_contract_contract_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi")),
                ("method", models.CharField(choices=[("CASH", "Peşin"), ("INSTALLMENT", "Vadeli/Taksit")], default="CASH", max_length=20)),
                ("currency", models.CharField(choices=[("TRY", "Türk Lirası"), ("USD", "Amerikan Doları"), ("EUR", "Euro")], default="TRY", max_length=3)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ("installment_count", models.PositiveSmallIntegerField(default=4)),
                ("first_due_date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "contract",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="payment_plan", to="production.contract"),
                ),
            ],
            options={
                "verbose_name": "Ödeme Planı",
                "verbose_name_plural": "Ödeme Planları",
            },
        ),
        migrations.CreateModel(
            name="PaymentInstallment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi")),
                ("installment_no", models.PositiveSmallIntegerField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=19)),
                ("currency", models.CharField(choices=[("TRY", "Türk Lirası"), ("USD", "Amerikan Doları"), ("EUR", "Euro")], default="TRY", max_length=3)),
                ("status", models.CharField(choices=[("PENDING", "Bekleyen"), ("PAID", "Ödendi"), ("CANCELLED", "İptal")], default="PENDING", max_length=20)),
                ("paid_at", models.DateField(blank=True, null=True)),
                (
                    "paid_transaction",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="paid_installments", to="finance.transaction"),
                ),
                (
                    "plan",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="installments", to="finance.paymentplan"),
                ),
            ],
            options={
                "verbose_name": "Taksit",
                "verbose_name_plural": "Taksitler",
                "ordering": ["due_date", "installment_no"],
                "unique_together": {("plan", "installment_no")},
            },
        ),
    ]
