# Generated by Django 6.0 on 2025-12-27

from decimal import Decimal

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_paymentplan_and_installments"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedExpense",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi")),
                ("name", models.CharField(max_length=200, verbose_name="Gider Adı")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=19,
                        validators=[MinValueValidator(Decimal("0.01"))],
                        verbose_name="Tutar",
                    ),
                ),
                ("currency", models.CharField(choices=[("TRY", "Türk Lirası"), ("USD", "Amerikan Doları"), ("EUR", "Euro")], default="TRY", max_length=3)),
                (
                    "due_day",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[MinValueValidator(1), MaxValueValidator(31)],
                        verbose_name="Ayın Kaçıncı Günü",
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.localdate, verbose_name="Başlangıç Tarihi")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="Bitiş Tarihi")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("notes", models.CharField(blank=True, default="", max_length=255, verbose_name="Not")),
            ],
            options={
                "verbose_name": "Sabit Gider",
                "verbose_name_plural": "Sabit Giderler",
                "ordering": ["name", "due_day"],
            },
        ),
    ]
