# Generated by Django 6.0 on 2025-12-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_fixed_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentplan",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymentinstallment",
            name="method",
            field=models.CharField(
                choices=[("CASH", "Nakit"), ("TRANSFER", "Havale/EFT"), ("POS", "POS/Kart"), ("CHEQUE", "Çek")],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PaymentReminder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi")),
                ("run_at", models.DateTimeField()),
                ("status", models.CharField(choices=[("PENDING", "Bekliyor"), ("SENT", "Gönderildi"), ("CANCELLED", "İptal")], default="PENDING", max_length=20)),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("recipient_role", models.CharField(blank=True, default="", max_length=20)),
                ("installment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reminders", to="finance.paymentinstallment")),
            ],
            options={
                "ordering": ["run_at", "id"],
            },
        ),
    ]
