# Generated by Django 6.0 on 2025-12-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_payment_installment_method_and_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='method',
            field=models.CharField(choices=[('CASH', 'Peşin'), ('INSTALLMENT', 'Vadeli/Taksit'), ('CHEQUE', 'Çek'), ('MIXED', 'Karma')], default='CASH', max_length=20),
        ),
    ]
