# Generated by Django 6.0 on 2025-12-26 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('name', models.CharField(max_length=200, verbose_name='Firma/Şahıs Adı')),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Bireysel'), ('CORPORATE', 'Kurumsal')], default='CORPORATE', max_length=20)),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='Vergi/TC No')),
                ('tax_office', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('risk_limit', models.DecimalField(decimal_places=2, default=0, help_text='Maksimum açık hesap limiti', max_digits=15)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('google_maps_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('proposal_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Taslak'), ('SENT', 'Müşteriye Gönderildi'), ('APPROVED', 'Onaylandı (Sözleşme Bekliyor)'), ('REJECTED', 'Reddedildi'), ('CONVERTED', 'Sözleşmeye Dönüştü')], default='DRAFT', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Geçerlilik Tarihi')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('currency', models.CharField(choices=[('TRY', 'Türk Lirası'), ('USD', 'Amerikan Doları'), ('EUR', 'Euro')], default='TRY', max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='crm.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Ürün/Taş Adı')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='En (cm)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Boy (cm)')),
                ('quantity', models.IntegerField(default=1, verbose_name='Adet')),
                ('waste_ratio', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Fire Oranı %')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Birim Fiyat')),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='İşçilik Maliyeti')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.proposal')),
            ],
        ),
    ]
