# Generated by Django 6.0 on 2025-12-26 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('inventory', '0004_slab_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='google_maps_link',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location_lat',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='location_lng',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='proposalitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='proposalitem',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='proposalitem',
            name='waste_ratio',
        ),
        migrations.AddField(
            model_name='customer',
            name='location_url',
            field=models.URLField(blank=True, verbose_name='Google Maps Konumu'),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='description',
            field=models.CharField(blank=True, help_text='Örn: Mutfak Tezgahı', max_length=200),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='fire_rate',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Fire Oranı %'),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.productdefinition'),
        ),
        migrations.AddField(
            model_name='proposalitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=19),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('COMPANY', 'Kurumsal Firma'), ('INDIVIDUAL', 'Bireysel Şahıs')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Müşteri/Firma Adı'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='risk_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Risk Limiti'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='TC / Vergi No'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_office',
            field=models.CharField(blank=True, max_length=100, verbose_name='Vergi Dairesi'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='currency',
            field=models.CharField(choices=[('TRY', 'TL'), ('USD', 'USD'), ('EUR', 'EUR')], default='TRY', max_length=3),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='proposalitem',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='İşçilik Tutarı'),
        ),
        migrations.AlterField(
            model_name='proposalitem',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='proposalitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='proposalitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='proposalitem',
            name='width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
