# Generated by Django 6.0 on 2025-12-27

from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_remove_customer_google_maps_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="include_tax",
            field=models.BooleanField(default=False, verbose_name="KDV Dahil"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=Decimal("20.00"), max_digits=5, verbose_name="KDV Oranı (%)"),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi")),
                ("date", models.DateField(verbose_name="Randevu Tarihi")),
                ("title", models.CharField(blank=True, default="", max_length=200, verbose_name="Başlık")),
                ("notes", models.TextField(blank=True, verbose_name="Not")),
                (
                    "customer",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="appointments", to="crm.customer"),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
    ]
