# Generated by Django 6.0 on 2025-12-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_proposal_tax_and_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("LEAD", "Potansiyel / Ön Kayıt"),
                    ("NEGOTIATION", "Görüşülüyor"),
                    ("ACTIVE", "Aktif / Çalışılıyor"),
                    ("PAYMENT_DUE", "Ödeme Bekleniyor"),
                    ("PASSIVE", "Pasif"),
                    ("BLACKLIST", "İptal / Kara Liste"),
                ],
                default="LEAD",
                max_length=20,
                verbose_name="Durum",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="segment",
            field=models.CharField(
                choices=[
                    ("STANDARD", "Standart"),
                    ("VIP", "VIP"),
                    ("RISKY", "Riskli"),
                ],
                default="STANDARD",
                max_length=20,
                verbose_name="Segment",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="internal_notes",
            field=models.TextField(blank=True, default="", verbose_name="Şirket İçi Notlar"),
        ),
    ]
