# Generated by Django 6.0 on 2025-12-27

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_customer_status_segment_notes"),
        ("inventory", "0004_slab_photo_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proposalitem",
            name="slab",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="inventory.slab"),
        ),
        migrations.AddField(
            model_name="appointment",
            name="source_type",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="appointment",
            name="source_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OfferApprovalFlow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi")),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("contract_id", models.PositiveIntegerField(blank=True, null=True)),
                ("payment_plan_id", models.PositiveIntegerField(blank=True, null=True)),
                ("work_order_ids", models.JSONField(blank=True, default=list)),
                ("reservation_ids", models.JSONField(blank=True, default=list)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("proposal", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="approval_flow", to="crm.proposal")),
            ],
            options={
                "verbose_name": "Teklif Onay Akışı",
                "verbose_name_plural": "Teklif Onay Akışları",
            },
        ),
        migrations.CreateModel(
            name="OfferAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma Tarihi")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Güncelleme Tarihi")),
                ("action", models.CharField(max_length=100)),
                ("message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("actor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("proposal", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="audit_logs", to="crm.proposal")),
            ],
            options={
                "verbose_name": "Teklif Onay Logu",
                "verbose_name_plural": "Teklif Onay Logları",
                "unique_together": {("proposal", "action")},
            },
        ),
    ]
