# Generated by Django 6.0 on 2025-12-27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_proposalitem_slab_and_approval_flow"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_customers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Müşteri Sorumlusu",
            ),
        ),
    ]
