# Generated by Django 6.0 on 2025-12-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_customer_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerapprovalflow',
            name='work_order_ids',
        ),
    ]
