# Generated by Codex on 2025-02-10

from django.db import migrations, models


def assign_numbers(apps, schema_editor):
    Customer = apps.get_model("crm", "Customer")
    Proposal = apps.get_model("crm", "Proposal")

    customer_ids = list(Customer.objects.order_by("id").values_list("id", flat=True))
    for idx, customer_id in enumerate(customer_ids, start=1):
        Customer.objects.filter(pk=customer_id).update(customer_number=idx)

    proposal_ids = list(Proposal.objects.order_by("id").values_list("id", flat=True))
    for proposal_id in proposal_ids:
        Proposal.objects.filter(pk=proposal_id).update(proposal_number=f"TMP-{proposal_id}")
    for idx, proposal_id in enumerate(proposal_ids, start=1):
        Proposal.objects.filter(pk=proposal_id).update(
            proposal_no=idx,
            proposal_number=str(idx),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_remove_offerapprovalflow_work_order_ids"),
    ]

    atomic = False

    operations = [
        migrations.AddField(
            model_name="customer",
            name="customer_number",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="proposal_no",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="proposal",
            name="work_summary",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Yapılacak İş (Özet)"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="stone_summary",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Taş Cinsi (Özet)"),
        ),
        migrations.AddField(
            model_name="proposal",
            name="delivery_type",
            field=models.CharField(
                choices=[("APPLICATION_INCLUDED", "Uygulama Dahil"), ("FACTORY_DELIVERY", "Fabrika Teslim")],
                default="FACTORY_DELIVERY",
                max_length=30,
                verbose_name="Teslimat Tipi",
            ),
        ),
        migrations.AddField(
            model_name="proposalitem",
            name="stone_type",
            field=models.CharField(blank=True, default="", max_length=200, verbose_name="Taş Cinsi"),
        ),
        migrations.AddField(
            model_name="proposalitem",
            name="size_text",
            field=models.CharField(blank=True, default="", max_length=100, verbose_name="Ebat"),
        ),
        migrations.AddField(
            model_name="proposalitem",
            name="total_measure",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Toplam"),
        ),
        migrations.AddField(
            model_name="proposalitem",
            name="total_unit",
            field=models.CharField(
                blank=True,
                choices=[("MTUL", "Mtül"), ("M2", "m²"), ("ADET", "Adet"), ("TAKIM", "Takım")],
                max_length=10,
                null=True,
                verbose_name="Birim",
            ),
        ),
        migrations.RunPython(assign_numbers, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="customer",
            name="customer_number",
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="proposal_no",
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
