# Generated by Codex on 2025-02-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_customer_number_and_proposal_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="status_color",
            field=models.CharField(
                choices=[
                    ("BLACK", "Siyah"),
                    ("RED", "Kırmızı"),
                    ("YELLOW", "Sarı"),
                    ("GREEN", "Yeşil"),
                ],
                default="GREEN",
                max_length=10,
                verbose_name="Statü",
            ),
        ),
    ]
